personajes = {
    "Harry Potter": "Gryffindor",
    "Ron Weasley": "Gryffindor",
    "Hermione Granger": "Gryffindor",
    "Draco Malfoy": "Slytherin",
    "Neville Longbottom": "Gryffindor",
    "Luna Lovegood": "Ravenclaw",
    "Cho Chang": "Ravenclaw",
    "Seamus Finnigan": "Gryffindor",
    "Dean Thomas": "Gryffindor",
    "Ginny Weasley": "Gryffindor",
    "Albus Dumbledore": "Gryffindor",
    "Severus Snape": "Slytherin",
    "Minerva McGonagall": "Gryffindor",
    "Remus Lupin": "Gryffindor",
    "Sirius Black": "Gryffindor",
    "Fred Weasley": "Gryffindor",
    "George Weasley": "Gryffindor",
    "Tom Riddle": "Slytherin",
    "Voldemort": "Slytherin",
    "Bellatrix Lestrange": "Slytherin",
    "Rubeus Hagrid": "Hufflepuff",
    "Cho Chang": "Ravenclaw",
    "Laverne Crabbe": "Slytherin",
    "Vincent Crabbe": "Slytherin",
    "Anthony Goldstein": "Ravenclaw",
    "Terry Boot": "Ravenclaw",
    "Michael Corner": "Ravenclaw",
    "Parvati Patil": "Gryffindor",
    "Lavender Brown": "Gryffindor",
    "Pansy Parkinson": "Slytherin",
    "Justin Finch-Fletchley": "Hufflepuff",
    "Evanna Lynch": "Ravenclaw",
    "Dobby": "Hufflepuff",
    "Kreacher": "Slytherin",
    "Hagrid": "Hufflepuff",
    "Filch": "Slytherin",
    "Peeves": "Ninguna",
    "Dumbledore": "Gryffindor",
    "Snape": "Slytherin",
    "McGonagall": "Gryffindor",
    "Lupin": "Gryffindor",
    "Black": "Gryffindor",
    "Weasley": "Gryffindor",
    "Riddle": "Slytherin",
    "Voldemort": "Slytherin",
    "Lestrange": "Slytherin",
    "Hagrid": "Hufflepuff",
    "Cho": "Ravenclaw",
    "Crabbe": "Slytherin",
    "Boot": "Ravenclaw",
    "Corner": "Ravenclaw",
    "Patil": "Gryffindor",
    "Brown": "Gryffindor",
    "Parkinson": "Slytherin",
    "Finch-Fletchley": "Hufflepuff",
    "Lynch": "Ravenclaw",
    "Dobby": "Hufflepuff",
    "Kreacher": "Slytherin",
}